export const useJoditConfig = {
    readonly: false,
    height: '300px',
    width: '100%',
    enableDragAndDropFileToEditor: true,
    uploader: { insertImageAsBase64URI: true },
    removeButtons: ['brush', 'file'],
    showXPathInStatusbar: false,
    showCharsCounter: false,
    showWordsCounter: false,
    toolbarAdaptive: true,
    toolbarSticky: true,
    toolbarButtons: [
        'source',
        '|',
        'bold',
        'italic',
        'underline',
        '|',
        'ul',
        'ol',
        '|',
        'link',
        'image',
        '|',
        'align',
        '|',
        'undo',
        'redo',
    ],
};